"""complete message

Revision ID: ecec44ccbd8a
Revises: 8ee1e9eff420
Create Date: 2020-04-26 08:42:43.557016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecec44ccbd8a'
down_revision = '8ee1e9eff420'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('complete_message', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'complete_message')
    # ### end Alembic commands ###
